<a href="https://colab.research.google.com/github/devunisathish/NASSCOM/blob/main/HANDSON2DAY1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#Matrix Creation & Basic Ops
import numpy as np
A = np.array([[2, 1], [0, 3]])
B = np.array([[1, 4], [2, 5]])
print("A + B =\n", A + B)
print("A transpose =\n", A.T)
print("A @ B =\n", A @ B) # Matrix multiplication

A + B =
 [[3 5]
 [2 8]]
A transpose =
 [[2 0]
 [1 3]]
A @ B =
 [[ 4 13]
 [ 6 15]]


In [10]:
#Identity & Inverse
I = np.eye(3)
print("Identity:\n", I)
# 3x3 identity matrix
A= np.array([[2, 1], [1, 3]])
A_inv = np.linalg.inv(A)
print("A inverse: \n", A_inv)
print("A @A_inv =\n", A @A_inv) # Should be identity

Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A inverse: 
 [[ 0.6 -0.2]
 [-0.2  0.4]]
A @A_inv =
 [[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


In [11]:
#Solving Ax = b
#Solve: 2x + y = 5, x + 3y = 7
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 7])
x = np.linalg.solve(A, b)
print("Solution:", x)
# More stable than inv (A)@b # [1.6, 1.8]
#Verify: A @ x should equal b
print("Check: A @ x =", A @ x)
# [5.0, 7.0]

Solution: [1.6 1.8]
Check: A @ x = [5. 7.]


Create a 3x3 system of equations from a real scenario (e.g., pricing 3 products given 3 customer orders).

## 3x3 System of Equations: Product Pricing Scenario

Imagine a small business selling three different types of fruit: Apples, Bananas, and Cherries. We have data from three customer orders, each containing a different combination of these fruits and the total cost of the order.

We want to determine the price per unit for each type of fruit.

Let:
- `x` = price per Apple
- `y` = price per Banana
- `z` = price per Cherry

**Order 1:** 2 Apples, 1 Banana, 3 Cherries = $11
**Order 2:** 4 Apples, 2 Bananas, 1 Cherry = $13
**Order 3:** 1 Apple, 3 Bananas, 2 Cherries = $10

This can be represented as a system of linear equations:

$2x + 1y + 3z = 11$
$4x + 2y + 1z = 13$
$1x + 3y + 2z = 10$

In [13]:
# Define the coefficient matrix A and the constant vector b

A = np.array([
    [2, 1, 3],
    [4, 2, 1],
    [1, 3, 2]
])

b = np.array([11, 13, 10])

# Solve the system of equations Ax = b for x
prices = np.linalg.solve(A, b)

print("Prices for Apples, Bananas, and Cherries (x, y, z) are:", prices)

# Verify the solution
print("\nVerification: A @ prices =", A @ prices)
print("Expected b =", b)

Prices for Apples, Bananas, and Cherries (x, y, z) are: [2.08 1.44 1.8 ]

Verification: A @ prices = [11. 13. 10.]
Expected b = [11 13 10]
