<a href="https://colab.research.google.com/github/devunisathish/NASSCOM-MODULE-1/blob/main/DAY3/DAY3Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")
# 1.1 Create a Pandas Series named 's1_1' from a list of numbers [10, 20, 30, 40, 50].
# 1.2 Create a 3x4 NumPy array named 'np_array1_2' with random integers between 1 and 100.
# 1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3' with columns 'A', 'B', 'C', 'D'.

# Your code for Task 1 here:
# 1.1 Create a Pandas Series named 's1_1'
s1_1 = pd.Series([10, 20, 30, 40, 50])
print("\nSeries s1_1:")
print(s1_1)

# 1.2 Create a 3x4 NumPy array named 'np_array1_2'
np_array1_2 = np.random.randint(1, 101, size=(3, 4))
print("\nNumPy array np_array1_2:")
print(np_array1_2)

# 1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3'
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])
print("\nDataFrame df1_3:")
print(df1_3)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---

Series s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy array np_array1_2:
[[92 15 54 29]
 [29 65 55 42]
 [95 21 73 93]]

DataFrame df1_3:
    A   B   C   D
0  92  15  54  29
1  29  65  55  42
2  95  21  73  93


In [2]:
# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")
# Create a DataFrame named 'df_sales' with 100 rows and the following columns:
# - 'Date': A range of dates from '2023-01-01' to '2023-04-09' (inclusive).
# - 'Region': Randomly chosen from ['East', 'West', 'North', 'South'].
# - 'Product': Randomly chosen from ['Laptop', 'Mouse', 'Keyboard', 'Monitor'].
# - 'Sales': Random integers between 100 and 1000.
# - 'Quantity': Random integers between 1 and 10.
# - Introduce 5 random NaN values in the 'Sales' column and 3 random NaN values in the 'Quantity' column.

# Your code for Task 2 here:
num_rows = 100

# 'Date' column
dates = pd.to_datetime(pd.date_range(start='2023-01-01', end='2023-04-09', periods=num_rows))

# 'Region' column
regions = np.random.choice(['East', 'West', 'North', 'South'], size=num_rows)

# 'Product' column
products = np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], size=num_rows)

# 'Sales' column
sales = np.random.randint(100, 1001, size=num_rows)

# 'Quantity' column
quantity = np.random.randint(1, 11, size=num_rows)

# Create the DataFrame
df_sales = pd.DataFrame({
    'Date': dates,
    'Region': regions,
    'Product': products,
    'Sales': sales,
    'Quantity': quantity
})

# Introduce NaN values
# For 'Sales' column (5 NaNs)
sales_nan_indices = np.random.choice(df_sales.index, size=5, replace=False)
df_sales.loc[sales_nan_indices, 'Sales'] = np.nan

# For 'Quantity' column (3 NaNs)
quantity_nan_indices = np.random.choice(df_sales.index, size=3, replace=False)
df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan

print("\ndf_sales head:")
print(df_sales.head())
print("\ndf_sales info:")
print(df_sales.info())
print("\nNaN counts:")
print(df_sales.isnull().sum())


--- Task 2: Synthetic Data Generation for Practice ---

df_sales head:
                           Date Region   Product  Sales  Quantity
0 2023-01-01 00:00:00.000000000  South  Keyboard  138.0       2.0
1 2023-01-01 23:45:27.272727272  North   Monitor  883.0       5.0
2 2023-01-02 23:30:54.545454545  North    Laptop  253.0      10.0
3 2023-01-03 23:16:21.818181818  South   Monitor  853.0       6.0
4 2023-01-04 23:01:49.090909090  North  Keyboard  878.0       2.0

df_sales info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Date      100 non-null    datetime64[ns]
 1   Region    100 non-null    object        
 2   Product   100 non-null    object        
 3   Sales     95 non-null     float64       
 4   Quantity  97 non-null     float64       
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 4.0+ KB
None

NaN counts:
Da

In [3]:
# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
# Use 'df_sales' from Task 2.
# 3.1 Select only the 'Region' and 'Sales' columns. Store it in 'df3_1'.
# 3.2 Select rows where 'Product' is 'Laptop'. Store it in 'df3_2'.
# 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500. Store it in 'df3_3'.
# 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor' (use .loc and .iloc). Store it in 'val3_4'.

# Your code for Task 3 here:
# 3.1 Select only the 'Region' and 'Sales' columns
df3_1 = df_sales[['Region', 'Sales']]
print("\n3.1 df3_1 (Region and Sales columns):")
print(df3_1.head())

# 3.2 Select rows where 'Product' is 'Laptop'
df3_2 = df_sales[df_sales['Product'] == 'Laptop']
print("\n3.2 df3_2 (Product is 'Laptop'):")
print(df3_2.head())

# 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500
df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]
print("\n3.3 df3_3 (Region is 'East' AND Sales > 500):")
print(df3_3.head())

# 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor'
# Find the index of the first 'Monitor' product
monitor_index = df_sales[df_sales['Product'] == 'Monitor'].index[0]
val3_4 = df_sales.loc[monitor_index, 'Sales'] # Using .loc
print("\n3.4 val3_4 (Sales value for the first 'Monitor' using .loc):", val3_4)


--- Task 3: Indexing and Slicing in DataFrames ---

3.1 df3_1 (Region and Sales columns):
  Region  Sales
0  South  138.0
1  North  883.0
2  North  253.0
3  South  853.0
4  North  878.0

3.2 df3_2 (Product is 'Laptop'):
                            Date Region Product  Sales  Quantity
2  2023-01-02 23:30:54.545454545  North  Laptop  253.0      10.0
10 2023-01-10 21:34:32.727272727   East  Laptop  342.0       2.0
14 2023-01-14 20:36:21.818181818   East  Laptop  542.0      10.0
18 2023-01-18 19:38:10.909090909  South  Laptop  877.0       1.0
19 2023-01-19 19:23:38.181818182  North  Laptop  436.0       5.0

3.3 df3_3 (Region is 'East' AND Sales > 500):
                            Date Region   Product  Sales  Quantity
9  2023-01-09 21:49:05.454545454   East  Keyboard  796.0       6.0
14 2023-01-14 20:36:21.818181818   East    Laptop  542.0      10.0
20 2023-01-20 19:09:05.454545454   East     Mouse  578.0       7.0
29 2023-01-29 16:58:10.909090909   East     Mouse  744.0       8.0
43 2023

In [4]:
# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
# Use 'df_sales' from Task 2 (which should have NaNs).
# 4.1 Check how many missing values are in each column. Store the result in 'missing_counts4_1'.
# 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column. Store the modified DataFrame in 'df4_2_filled'.
# 4.3 Drop rows that have any missing values in 'df_sales'. Store the result in 'df4_3_dropped'.

# Your code for Task 4 here:
# 4.1 Check how many missing values are in each column
missing_counts4_1 = df_sales.isnull().sum()
print("\n4.1 Missing values in each column:")
print(missing_counts4_1)

# 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column
mean_sales = df_sales['Sales'].mean()
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(mean_sales)
print("\n4.2 df4_2_filled (Sales NaNs filled with mean):")
print(df4_2_filled.head())
print("Missing values after filling Sales:")
print(df4_2_filled.isnull().sum())

# 4.3 Drop rows that have any missing values in 'df_sales'
df4_3_dropped = df_sales.dropna()
print("\n4.3 df4_3_dropped (Rows with any NaNs dropped):")
print(df4_3_dropped.head())
print("Missing values after dropping rows:")
print(df4_3_dropped.isnull().sum())


--- Task 4: Data Cleaning (Handling Missing Values) ---

4.1 Missing values in each column:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

4.2 df4_2_filled (Sales NaNs filled with mean):
                           Date Region   Product  Sales  Quantity
0 2023-01-01 00:00:00.000000000  South  Keyboard  138.0       2.0
1 2023-01-01 23:45:27.272727272  North   Monitor  883.0       5.0
2 2023-01-02 23:30:54.545454545  North    Laptop  253.0      10.0
3 2023-01-03 23:16:21.818181818  South   Monitor  853.0       6.0
4 2023-01-04 23:01:49.090909090  North  Keyboard  878.0       2.0
Missing values after filling Sales:
Date        0
Region      0
Product     0
Sales       0
Quantity    3
dtype: int64

4.3 df4_3_dropped (Rows with any NaNs dropped):
                           Date Region   Product  Sales  Quantity
0 2023-01-01 00:00:00.000000000  South  Keyboard  138.0       2.0
1 2023-01-01 23:45:27.272727272  North   Monitor  883.0       5.0
2 2023-01-02 

In [5]:
# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
# Use 'df_sales' (the original one with NaNs)
# 5.1 Create a new column 'Total_Revenue' which is 'Sales' * 'Quantity'.
#     (Be mindful of NaNs, the result should also be NaN where either Sales or Quantity is NaN).
# 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order. Store it in 'df5_2_sorted'.
# 5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity' for each region.
#     Store the result in 'df5_3_grouped_region'.
# 5.4 Group 'df_sales' by 'Product' and find the average 'Sales' for each product.
#     Store the result in 'df5_4_grouped_product'.

# Your code for Task 5 here:
# 5.1 Create a new column 'Total_Revenue'
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']
print("\n5.1 df_sales with 'Total_Revenue' column (head):")
print(df_sales.head())

# 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order
df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'], ascending=[True, False])
print("\n5.2 df5_2_sorted (head):")
print(df5_2_sorted.head())

# 5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity'
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()
print("\n5.3 df5_3_grouped_region:")
print(df5_3_grouped_region)

# 5.4 Group 'df_sales' by 'Product' and find the average 'Sales'
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()
print("\n5.4 df5_4_grouped_product:")
print(df5_4_grouped_product)


--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---

5.1 df_sales with 'Total_Revenue' column (head):
                           Date Region   Product  Sales  Quantity  \
0 2023-01-01 00:00:00.000000000  South  Keyboard  138.0       2.0   
1 2023-01-01 23:45:27.272727272  North   Monitor  883.0       5.0   
2 2023-01-02 23:30:54.545454545  North    Laptop  253.0      10.0   
3 2023-01-03 23:16:21.818181818  South   Monitor  853.0       6.0   
4 2023-01-04 23:01:49.090909090  North  Keyboard  878.0       2.0   

   Total_Revenue  
0          276.0  
1         4415.0  
2         2530.0  
3         5118.0  
4         1756.0  

5.2 df5_2_sorted (head):
                           Date Region   Product  Sales  Quantity  \
0 2023-01-01 00:00:00.000000000  South  Keyboard  138.0       2.0   
1 2023-01-01 23:45:27.272727272  North   Monitor  883.0       5.0   
2 2023-01-02 23:30:54.545454545  North    Laptop  253.0      10.0   
3 2023-01-03 23:16:21.818181818  South   Monitor  853.0